const firstName = 'Shiwanee';
const lastName = 'Gupta';
const age = '25';
const dateOfBirth = '06/06/1989';
const address = '5th Avenue';
console.log('firstName: ', firstName);
console.log('lastName: ', lastName);
console.log('age: ', age);
console.log('dateOfBirth: ', dateOfBirth);
console.log('address: ', address);
