var firstName = 'Shiwanee' ;
var lastName = 'Gupta';
var age = '25';
var dateOfBirth = '06/06/1989';
var address = '5th Avenue';
console.log(firstName);
console.log(lastName);
console.log(age);
console.log(dateOfBirth);
console.log(address);