let age = 25;
let phone = 3065143710;
let streetName = '5th avenue';
let streetNumber = 325;
let firstMessage = `I'm ${age} years old`;
let secondMessage = `My phone number is:${phone}`;
let thirdmessage = `I live on ${streetNumber} ${streetName}`;
console.log(firstMessage);
console.log(secondMessage);
console.log(thirdmessage);
